version: '3.8'

services:
  backend:
    build: ./backend    
    networks:
      - app-network
    expose:
      - "8000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.production

networks:
  app-network:
    driver: bridge
